import { type ClientMessage, type ServerMessage } from '../src/shared/play.js';
interface PlayServerDependencies {
    sendToSession: (sessionId: string, message: ServerMessage) => void;
    disconnectGracePeriodMs?: number;
    setTimeout?: (callback: () => void, delayMs: number) => ReturnType<typeof globalThis.setTimeout>;
    clearTimeout?: (timeoutId: ReturnType<typeof globalThis.setTimeout>) => void;
}
export declare class PlayServer {
    private readonly dependencies;
    private readonly rooms;
    private readonly gameRoomIds;
    private readonly sessionRoomIds;
    private readonly sessionNames;
    private readonly knownSessionIds;
    private readonly debugUnlockedSessions;
    private readonly pendingDisconnectTimers;
    private readonly disconnectGracePeriodMs;
    private readonly setTimeoutFn;
    private readonly clearTimeoutFn;
    constructor(dependencies: PlayServerDependencies);
    handleHello(sessionId: string, playerName: string): void;
    handleDisconnect(sessionId: string): void;
    private finalizeDisconnect;
    private clearPendingDisconnect;
    handleMessage(sessionId: string, message: Exclude<ClientMessage, {
        type: 'hello';
    }>): void;
    private createRoom;
    private unlockDebugMode;
    private createDebugRoom;
    private joinRoom;
    private leaveRoom;
    private updateRoomSettings;
    private addDebugPlayer;
    private removeDebugPlayer;
    private selectDeck;
    private startGame;
    private applyGameAction;
    private takeOwnedCard;
    private placeOwnedCard;
    private getNextPlayer;
    private applyPlayerDesignation;
    private getControllablePermanent;
    private getStackMembers;
    private normalizeStack;
    private setStackPosition;
    private setPermanentStack;
    private unstackPermanent;
    private getAutoBattlefieldPosition;
    private buildInitialCommandZone;
    private emitRoomSnapshots;
    private emitGameSnapshots;
    private buildRoomSnapshot;
    private emitRoomDirectorySnapshots;
    private buildRoomDirectoryEntry;
    private buildGameSnapshot;
    private toTableCardSnapshot;
    private toBattlefieldCardSnapshot;
    private toStackItemSnapshot;
    private recordEvent;
    private generateUniqueRoomId;
    private createRoomPlayer;
    private createDebugPlaceholderPlayer;
    private getPlayerName;
    private getRoomBySession;
    private getRoomByGameId;
    private deleteRoom;
    private emitError;
    private normalizeDeckSelection;
    private formatZoneLabel;
}
export {};
